### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by yavyx** [UBC-MDS/rimager#23]
- Great job overall, README is clear and the functions make sense. Some functions could use more detailed descriptions.
- Is `.Rapp.history` necessary in your `R` directory?
- Missing Zoe's e-mail in contributors.

**Comment by dataubc** [comment]
Thank you Javier, will update the function with more descriptions .

**Comment by zoepan00** [comment]
- Missing Zoe's e-mail in contributors. (added #25)

**Comment by zoepan00** [comment]
.Rapp.history deleted #31

**Comment by Keanna-K** [comment]
Added additional details for the img_filter and reducolor functions in the README file #29
