### ISSUE TITLE
Update README.md file

### ISSUE THREAD

**Issue by Keanna-K** [UBC-MDS/rimager#5]
- [x] summary paragraph giving a high-level description of the project
- [x] list of the functions included in the package
- along with a 1-2 sentence description of each function
- [x] paragraph describing where our package fits into the R ecosystem 
- ie. link similar packages / functions

**Comment by Keanna-K** [comment]
From pull request #12, summary and package fit paragraphs added to README file.

**Comment by zoepan00** [comment]
Done
